### PR TITLE
Issue #335: allow a different background on focus.

### PR DESCRIPTION
**Pull request by Chrriis**
This pull request allows to have a different background on focus for TextField, PasswordField, TextArea and ComboBox.

FocusedBackground

Test code:
```Java
public static void main(String[] args) throws Exception {
	UIManager.setLookAndFeel(new FlatLightLaf());
	UIManager.getDefaults().put("Panel.background", Color.WHITE);
	UIManager.getDefaults().put("TextField.background", new Color(0xf0f0f0));
	UIManager.getDefaults().put("TextField.focusedBackground", Color.WHITE);
	UIManager.getDefaults().put("PasswordField.background", new Color(0xf0f0f0));
	UIManager.getDefaults().put("PasswordField.focusedBackground", Color.WHITE);
	UIManager.getDefaults().put("TextArea.background", new Color(0xf0f0f0));
	UIManager.getDefaults().put("TextArea.focusedBackground", Color.WHITE);
	UIManager.getDefaults().put("ComboBox.background", new Color(0xf0f0f0));
	UIManager.getDefaults().put("ComboBox.focusedBackground", Color.WHITE);
	UIManager.getDefaults().put("ComboBox.buttonBackground", new Color(0xf0f0f0));
	UIManager.getDefaults().put("ComboBox.buttonFocusedBackground", Color.WHITE);
	UIManager.getDefaults().put("ComboBox.editableBackground", new Color(0xf0f0f0));
	JFrame frame = new JFrame();
	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	JPanel centerPane = new JPanel(new GridBagLayout());
	centerPane.setBorder(BorderFactory.createEmptyBorder(20, 40, 20, 40));
	int y = 0;
	centerPane.add(new JTextField("Sample text field", 14), new GridBagConstraints(0, y++, 1, 1, 0, 0, GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(0, 0, 0, 0), 0, 0));
	centerPane.add(new JPasswordField("Password field", 14), new GridBagConstraints(0, y++, 1, 1, 0, 0, GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(5, 0, 0, 0), 0, 0));
	centerPane.add(new JScrollPane(new JTextArea("Sample text area", 5, 14)), new GridBagConstraints(0, y++, 1, 1, 0, 0, GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(5, 0, 0, 0), 0, 0));
	JComboBox<String> combo = new JComboBox<>(new String[] {"Item 1", "Item 2", "Item 3"});
	combo.setEditable(true);
	centerPane.add(combo, new GridBagConstraints(0, y++, 1, 1, 0, 0, GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(5, 0, 0, 0), 0, 0));
	JComboBox<String> combo2 = new JComboBox<>(new String[] {"Item 1", "Item 2", "Item 3"});
	centerPane.add(combo2, new GridBagConstraints(0, y++, 1, 1, 0, 0, GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(5, 0, 0, 0), 0, 0));
	frame.getContentPane().add(centerPane);
	frame.pack();
	frame.setLocationByPlatform(true);
	frame.setVisible(true);
}
```

### CODE REVIEW

**Comment by DevCharly** [comment]
Thanks @Chrriis for the contribution.

I've merged it with some extensions/modifications:
- also support JSpinner, JTextPane and JEditorPane
- ComboBox: if `ComboBox.buttonFocusedBackground` is not set, use `ComboBox.focusedBackground` for button background
- ComboBox: added `ComboBox.popupFocusedBackground` (instead of using `ComboBox.focusedBackground`)
- if component background color is not an instance of `UIResource` than always use it, even if focused

Because of the last point, you need to replace `new Color(...)` with `new ColorUIResource(...)` in your sample code (at least for the `.background` values).

**Comment by Chrriis** [comment]
Thanks for merging the PR! Our UI is a lot better with this!

I have one comment/question: it seems that when a text field is not editable, it does not get the focused background, even if it is focused (which is a change from my original implementation):
https://github.com/JFormDesigner/FlatLaf/blob/8a72b30cbc41637e0e216f2b4771c41478c6b893/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTextFieldUI.java#L206-L208

For me, changing the background is like changing the color of the border on focus. The cursor indicates that it is not editable but the background should change. Can you consider having the focusedBackground also when not editable? Or an additional property to allow that behavior?

**Comment by DevCharly** [comment]
> For me, changing the background is like changing the color of the border on focus.

Yes, that makes sense.

> Can you consider having the focusedBackground also when not editable? 

Done.

BTW I've recently renamed `ComboBox.popupFocusedBackground` to `ComboBox.popupBackground` because this has nothing to do with focus.

**Comment by Chrriis** [comment]
> > Can you consider having the focusedBackground also when not editable?
> 
> Done.

Thanks a lot!

> BTW I've recently renamed `ComboBox.popupFocusedBackground` to `ComboBox.popupBackground` because this has nothing to do with focus.

As a matter of fact, I saw that commit 5 minutes before this comment, and I had already adapted my code to be ready for it! 😉 

Thanks again for the great work!

**Pull request merged**
