### PR TITLE
Replace svgSalamander with jsvg

### PR DESCRIPTION
**Pull request by weisJ**
See #664

### CODE REVIEW

**Comment by rogerbj** [comment]
@weisJ Great work! Just tried the **FlatLafDemo** and if any `ColorFilter` has been set using `FlatSVGIcon.setColorFilter()` or `FlatSVGIcon.ColorFilter.setMapper()`, nothing happens with jsvg. This can be tested in the **FlatLafDemo** and in the **Extras** tab.

**Comment by rogerbj** [comment]
@weisJ I also ran into a problem in `FlatSVGIcon.loadFromStream()`:

```URI dummyUri = new URI( "inputStreamSVG", "/flatlaf-stream-" + streamNumber++, null );```

It produces an **"Invalid protocol: inputStreamSVG"** error. 

Except for this and my other report it works a lot better with randomly tested SVGs as opposed with SvgSalmander that fail with those.

**Comment by DevCharly** [comment]
@weisJ many thanks for the PR and for JSVG 👍 
@rogerbj thanks for testing.

I've reviewed it and fixed in color filter and loading from input stream issues.
Have also simplified the code a little bit by replacing internal use of URI with URL.
(URI was used/required for svgSalamander)

Will test this PR and JSVG in some other projects in the next weeks...

**Comment by weisJ** [comment]
Note that I had deliberately not changed the cache to take URLs as keys due to this problem: https://errorprone.info/bugpattern/URLEqualsHashCode

**Comment by DevCharly** [comment]
Many thanks for this hint. Didn't know that. Changed the cache key from URL to String to avoid that.

**Pull request merged**
